### ISSUE TITLE
Test FEniCS adapter

### ISSUE THREAD

**Issue by BenjaminRodenberg** [precice/systemtests#10]
As a first step we should set up and run the two tutorials for the FEniCS adapter in our system test framework.

- [x] [partitioned heat](https://github.com/precice/tutorials/tree/master/HT/partitioned-heat/fenics-fenics) #79 
- [ ] [flow over heated plate](https://github.com/precice/tutorials/tree/master/CHT/flow-over-plate/buoyantPimpleFoam-fenics) #81 
- [ ] new FSI cases #81 

After that we should also create some reference solutions and compare the output of the test to them.

**Comment by shkodm** [comment]
@RafalKulaga , @BenjaminRueth , What is the progress on it? I would then add this tests at the part of testing(  [this issue](https://github.com/precice/fenics-adapter/issues/24) ) of fenics-adapter, using #22

**Comment by RafalKulaga** [comment]
FEniCS adpater is working with both scenarios. Is that what you meant @shkodm ?

**Comment by BenjaminRodenberg** [comment]
Currently, there are no systemtests with the tutorial cases for the FEniCS adapter. We have some unit tests (https://github.com/precice/fenics-adapter/issues/24), but this is a different topic.

@RafalKulaga With systemtests we refer to tests like [this one](https://github.com/precice/systemtests/tree/master/Test_of-of.Ubuntu1604). Here, we use docker to run a tutorial case and compare it to reference results. Ideally, system tests are run automatically via travis after each commit; just like unit tests. The example above shows a system test for the heated plate tutorial with OpenFOAM-OpenFOAM.

**Comment by BenjaminRodenberg** [comment]
#79 adds testing for the partitioned heat equation. #81 will hopefully follow soon and add tests for CHT and FSI.

**Comment by BenjaminRodenberg** [comment]
Do we still want to add tests for all the CHT/FSI FEniCS-OpenFOAM tutorials mentioned above? Currently these tutorial cases are untested.

**Comment by BenjaminRodenberg** [comment]
Let's close this overview issue and work on the missing cases in #81
