### ISSUE TITLE
run compileAndTest.py somewhere in systemtests?

### ISSUE THREAD

**Issue by BenjaminRodenberg** [precice/systemtests#13]
[`compileAndTest.py`](https://github.com/precice/precice/blob/develop/tools/compileAndTest.py) is currently not run in any system test. Should we add a test which executes this script?

**Comment by BenjaminRodenberg** [comment]
`compileAndTest.py` is covered by Travis, currently.

**Comment by MakisH** [comment]
We also want to run systest with Travis, so should be included. Also, they should be independent.

**Comment by BenjaminRodenberg** [comment]
Currently the test breaks. Are we doing something wrong with docker? Is the behaviour inside a docker container identical to the observed behaviour, if we run the test without docker?

**Comment by shkodm** [comment]
Do we really need this test? We already build and run tests, when we test preCICE on travis in its own repo. So I am not sure if testing again here is needed. 

In either case,  I reproduced the behaviour on Travis for both Ubuntu [16.04](https://travis-ci.org/shkodm/systemtests/jobs/462474464)  and [18.04](https://travis-ci.org/shkodm/systemtests/jobs/462474469). Errors are somehow related to MPI: 

* 18.04 
> [ee25ea56a311:00008] PACK-PMIX-VALUE: UNSUPPORTED TYPE 0
[ee25ea56a311:00008] PMIX ERROR: ERROR in file src/server/pmix_server.c at line 1956
[ee25ea56a311:00015] OPAL ERROR: Timeout in file base/pmix_base_fns.c at line 195
[ee25ea56a311:15] *** An error occurred in MPI_Comm_connect
[ee25ea56a311:15] *** reported by process [1415249921,2]
[ee25ea56a311:15] *** on communicator MPI_COMM_SELF
[ee25ea56a311:15] *** MPI_ERR_UNKNOWN: unknown error
[ee25ea56a311:15] *** MPI_ERRORS_ARE_FATAL (processes in this communicator will now abort,
[ee25ea56a311:15] ***    and potentially your MPI job) 
* 16.04
> 7585aae71d78:00011] [[53728,1],0] ORTE_ERROR_LOG: Data unpack would read past end of buffer in file dpm_orte.c at line 406
[7585aae71d78:11] *** An error occurred in MPI_Comm_accept
[7585aae71d78:11] *** reported by process [3521118209,0]
[7585aae71d78:11] *** on communicator MPI_COMM_SELF
[7585aae71d78:11] *** MPI_ERR_UNKNOWN: unknown error
[7585aae71d78:11] *** MPI_ERRORS_ARE_FATAL (processes in this communicator will now abort,
[7585aae71d78:11] ***    and potentially your MPI job)

**Comment by floli** [comment]
Yes, we should have a system test that just runs the normal precice included test and it should be independent from Travis, since you want to run it one your local machine as part of the big system test suite. It's included in https://github.com/precice/systemtests/blob/master/Test_compile-and-test/Dockerfile.

We are aware of the failures on some versions of Ubuntu, but this issue is not the right place to discuss this. Please refer to the appropriate issues in the precice repo, e.g. https://github.com/precice/precice/issues/103
