### ISSUE TITLE
Unclear error message produced by "awk"

### ISSUE THREAD

**Issue by BenjaminRodenberg** [precice/systemtests#134]
This line of code

https://github.com/precice/systemtests/blob/f9c5ac902029da88599a8ca970f4607498dd95da/silent_compose.sh#L10

produces a very confusing and unclear error message:

https://travis-ci.org/precice/systemtests/jobs/621025195#L677-L711

In the end the test exits successfully (which is maybe even worse?).

**Comment by MakisH** [comment]
Is this the `silent_compose.sh` or the [compare_results.sh](https://github.com/precice/systemtests/blob/ec4ef9d4aedd0087dfb3a8ed98fdf7a1267c7751/compare_results.sh#L8)? I think it's the latter.

**Comment by fsimonis** [comment]
Division by zero sounds very much like a problem in the comparison

https://github.com/precice/systemtests/blob/f9c5ac902029da88599a8ca970f4607498dd95da/compare_results.sh#L67-L77
