### ISSUE TITLE
Replace workaround in nutils-of test

### ISSUE THREAD

**Issue by Eder-K** [precice/systemtests#156]
https://github.com/precice/systemtests/blob/14fdfe8d22756e68dec7cfd8bc58743b3c94b899/tests/TestCompose_nutils-of.Ubuntu1804/docker-compose.yml#L13

The `sleep 10` command in the docker-compose file of this test serves as a temporary hack to enforce the starting order of the participants. It should be replaced by an actual fix.

**Comment by MakisH** [comment]
Related to #148, see more discussion there: https://github.com/precice/systemtests/pull/148#issuecomment-577683073
