### ISSUE TITLE
Fix [16.04 PETSc] OpenFOAM - Calculix test

### ISSUE THREAD

**Issue by Eder-K** [precice/systemtests#158]
This test is currently marked as allowed failure since it depends on the docker image that gets generated in the Ubuntu 16.04.home PETSc preCICE build (which currently fails #139).

This test should be looked at after #139 has been resolved.

**Comment by BenjaminRodenberg** [comment]
I manually pushed a new image to dockerhub, where preCICE is build with PETSc (**ignoring failing tests!**) to bypass the dependency on #139 . [Using this image the test works.](https://travis-ci.org/precice/systemtests/jobs/646351899)
