### ISSUE TITLE
Elastictube1D tests occasionally fail

### ISSUE THREAD

**Issue by Eder-K** [precice/systemtests#223]
From checking the [recent cron jobs](https://travis-ci.org/github/precice/systemtests/builds/688375972), it seems that the elastictube tests fail at times due to some text difference in one particular line in both the Fluid.log and Solid.log files.

**Comment by MakisH** [comment]
What difference exactly? Do you already know the origin?

**Comment by Eder-K** [comment]
It turned out that the compare script detected a change in the preCICE revision. I [adapted the script accordingly](https://github.com/precice/systemtests/pull/224).
