### ISSUE TITLE
Missing tests for Ubuntu 20.04

### ISSUE THREAD

**Issue by MakisH** [precice/systemtests#245]
We currently don't test on Ubuntu 20.04, a popular choice among our users, which [we have agreed to include also in our GitHub Actions test matrix](https://github.com/precice/precice/issues/713#issuecomment-614500090).

Maybe until then, it would be good to add some step with Ubuntu 20.04 (e.g. build with all dependencies on, install the debian package, build the OpenFOAM adapter, run an OpenFOAM-OpenFOAM tutorial).

This we can do already now, but we should reconsider our test matrix in the future (not now).

**Comment by BenjaminRodenberg** [comment]
Directly related #222

Somehow similar direction #97

**Comment by Eder-K** [comment]
Closed by #222 . Note that we ultimately decided to run two tutorials on 20.04 for now: deal.II-OpenFOAM and SU2-CalculiX. Accordingly, Ubuntu 20.04 builds for the four adapters and one preCICE build using the package install have been added.
