### ISSUE TITLE
Do not hardcode Ubuntu

### ISSUE THREAD

**Issue by floli** [precice/systemtests#25]
The recent pull request #21 hard coded ubuntu in the code.

Hard coding for a single Linux distribution is not the way to go and we eventually want to test on/for other distributions as well. Please remove it.

**Comment by shkodm** [comment]
Good idea, I don't remember why I hardcoded it. WIll be fixed.

**Comment by floli** [comment]
Great!

Please also take https://github.com/precice/systemtests/issues/14 into account. @BenjaminRueth  and me worked on a scheme to bring base (precice) dockerfiles together with dockerfiles of solvers and documented it in the issue. Implementing shouldn't be too hard and there is already some work from @BenjaminRueth. If you see limitations of that scheme, please comment there, but try to follow it.
