### ISSUE TITLE
MPI Errors in 18.04 bindings and 18.04 elastictube-python test

### ISSUE THREAD

**Issue by Eder-K** [precice/systemtests#262]
See the following reference builds:
- [18.04 Bindings](https://travis-ci.org/github/precice/systemtests/jobs/745223860#L417)
- [18.04 Elastictube1D - Python](https://travis-ci.org/github/precice/systemtests/jobs/745223866#L538)

Both tests seem to fail due to the same underlying `MPI opal_init` error.

**Comment by BenjaminRodenberg** [comment]
I think that this happens due to the latest changes in the python bindings. I can take care of it and report here as soon as I've found out what's going wrong.

**Comment by BenjaminRodenberg** [comment]
https://github.com/precice/python-bindings/issues/72 is fixed via https://github.com/precice/python-bindings/pull/73. From my point of view the tests should work now. Can you run the test again?

**Comment by Eder-K** [comment]
Thanks for the quick work, the [bindings/elastictube systests are working again](https://travis-ci.org/github/precice/systemtests/builds/745432224). :+1: 

As mentioned in https://github.com/precice/python-bindings/issues/72, there might be more to this problem though. I will close this issue for now, as the systemtest side seems resolved. Feel free to reopen this if the spack fix causes trouble.

On another note, I just realized that there is no functionality in `trigger_systemtest.py` to launch tests from the elastictube repository. It might be worth to add it if it turns out that more testing needs to be done. Let's discuss that in another issue (#263).
