### ISSUE TITLE
Reduce the FSI SU2-CalculiX case runtime

### ISSUE THREAD

**Issue by MakisH** [precice/systemtests#33]
The current case takes around 23min on Travis, for 400 time steps of 0.01s (4s). Let's reduce this to e.g. 100 time steps.

https://github.com/precice/tutorials/blob/master/FSI/flap_perp/SU2-CalculiX/precice-config-serial.xml#L44

Since the systemtests take the configuration files from the tutorial, let's add a text-replace command to only affect the system tests.

**Comment by shkodm** [comment]
This is no longer relevant, due to the different build procedure we have.
