### ISSUE TITLE
Reduce the CHT OpenFOAM-CalculiX case runtime

### ISSUE THREAD

**Issue by MakisH** [precice/systemtests#34]
The current case takes around 12min on Travis, for 500 iterations (steady-state simulation, see [L. Cheung's thesis](https://www5.in.tum.de/pub/Cheung2016_Thesis.pdf) [1], Figure 6.7 (page 71)). Let's reduce this to 350 iterations. 

https://github.com/precice/tutorials/blob/master/CHT/heat_exchanger/buoyantSimpleFoam-CalculiX/precice-config_serial.xml#L84

Since the systemtests take the configuration files from the tutorial, let's add a text-replace command to only affect the system tests.

[1] Lucia Cheung Yau. Conjugate heat transfer with the multiphysics coupling library preCICE. Master’s thesis, Department of Informatics, Technical University of Munich, 2016.

**Comment by shkodm** [comment]
This is no longer relevant, due to the different build procedure we have.
