### ISSUE TITLE
Build preCICE images with CMake instead of SCons

### ISSUE THREAD

**Issue by MakisH** [precice/systemtests#37]
We currently build our base preCICE images with SCons:

https://github.com/precice/systemtests/blob/1475ddf5d3108931b0f392ce088e8598db7767d0/Dockerfile.Ubuntu1604#L46

We should [build these with CMake](https://github.com/precice/precice/wiki/Building:-Using-Cmake).

- [x] Build with CMake on Ubuntu 16.04
- [x] Build with CMake on Ubuntu 18.04

We could still have one target to build with SCons for a while, but we should treat CMake as our default.

**Comment by shkodm** [comment]
This issue is no longer relevant, since we build using CMake after https://github.com/precice/systemtests/pull/54.

I am closing it.

**Comment by floli** [comment]
Reopen because the Arch docker image still uses SCons.
