### ISSUE TITLE
Add ccache to base images

### ISSUE THREAD

**Issue by fsimonis** [precice/systemtests#52]
To add ccache in the system tests, we need to do the following:

1) Add a cached directory for ccache in Travis
2) Bind `$HOME/.ccache` form inside the docker base images to the cached directory in travis.
3) Install [ccache](https://ccache.samba.org/download.html) in the base images and add `-DCMAKE_CXX_COMPILER_LAUNCHER=ccache` to the preCICE configuration.

**Comment by shkodm** [comment]
This is no longer relevant. I am closing.
