### ISSUE TITLE
Systemtests should rebuild the base image when the HEAD of  branches change

### ISSUE THREAD

**Issue by fsimonis** [precice/systemtests#53]
The base images should be parameterized using the commit hash, not the branch name (or both).
This way, the base images properly rebuild after a push to the branch.

We can use `rev-parse` after cloning into a bare repository to get this inside `local_test.py` for the `branch`option and add a `--commit` option.

**Comment by shkodm** [comment]
This is not needed, as with `local_test.py` we can specify `--force-rebuild` that rebuilds image and on Travis images are rebuilt anyway.
