### ISSUE TITLE
Add test for OpenFOAM Nearest-Projection

### ISSUE THREAD

**Issue by MakisH** [precice/systemtests#65]
When https://github.com/precice/openfoam-adapter/pull/46 is merged (very soon), we should also add a system test for the `openfoam-adapter/tutorials/CHT/flow-over-plate/buoyantPimpleFoam-laplacianFoam_nearest-projection` case.

This tests different components of preCICE and, most importantly, different components of the OpenFOAM adapter.

**Comment by shkodm** [comment]
It is easy to add, after #80  is merged. But what should be the naming convention here? We already have `of-of` test. This is also related to #32. 

Maybe something like `of-of_np` (`np` - for nearest projection? ). We can have similar scheme for openFOAM-Calculix (`of-ccx_fsi`)?

**Comment by shkodm** [comment]
Update: Actually I've already added it locally, with the naming convention proposed above and it works fine. I will open a pull request after #80 is merged.
