### ISSUE TITLE
Add system test for deal.II tutorials

### ISSUE THREAD

**Issue by davidscn** [precice/systemtests#67]
The first tutorial case for deal.II-OpenFOAM (precice/tutorials#31) is currently reviewed and will be merged soon. There will be another tutorial case (FSI3). We should at least create a system test for one of the tutorial cases. This will also cover a system test for the [deal.II building](https://github.com/precice/dealii-adapter/wiki/Building).

**Comment by shkodm** [comment]
I will do it and test deal.ii adapter on the way.

**Comment by shkodm** [comment]
**Status**: I developed tests locally and everything seems to work. Building deal.ii takes way too much time, so I will think of way around it. I will push my branch and close the issue, once https://github.com/precice/tutorials/pull/31 is merged (and once I will have faster build...)

**Comment by davidscn** [comment]
The tutorial case is now merged. It also includes the requested `Allrun` script.

**Comment by shkodm** [comment]
I tested, and everything runs smoothly. I will open PR in a moment.
