### ISSUE TITLE
Remove duplicate code in Test_bindings*

### ISSUE THREAD

**Issue by BenjaminRodenberg** [precice/systemtests#68]
These following two files contain a lot of duplicate code:

* https://github.com/precice/systemtests/blob/master/Test_bindings.Ubuntu1804/Dockerfile

* https://github.com/precice/systemtests/blob/master/Test_bindings/Dockerfile

Can we factor this out?

**Comment by Eder-K** [comment]
The two bindings tests have been unified in #222. There now only exists a singular `Test_bindings` folder, which gets launched with differing `from` build arguments depending on which base version is specified.
