### ISSUE TITLE
Add Nutils CHT tutorial as system test

### ISSUE THREAD

**Issue by uekerman** [precice/systemtests#74]
Since a few weeks, there is also a tutorial with Nutils. 
https://github.com/precice/tutorials/tree/master/CHT/flow-over-plate/buoyantPimpleFoam-nutils
Would be great to also have this one as a system test.

Please note: There is no such thing as a Nutils adapter. Nutils is a FEM framework just as FEniCS, but we directly call the preCICE API from the Nutils application script.

**Comment by shkodm** [comment]
I will try to set it up

**Comment by shkodm** [comment]
Update: I managed to set it up, it runs fine, I will open PR after #80 is merged.
