### ISSUE TITLE
Confusion with lower/upper case branches and tags in docker

### ISSUE THREAD

**Issue by BenjaminRodenberg** [precice/systemtests#77]
Docker only allows lower case tags. Since we are using tags for identifying the branches or baseimages, we have to convert mixed case names to lower case names. This leads to a easy-to-break composition of tags:

https://github.com/precice/systemtests/blob/bf39313461b899b49bc47b5e4ad443259d5bfe87/.travis.yml#L19-L26

At some points, this conversion is already handled properly by our python scripts:

https://github.com/precice/systemtests/blob/bf39313461b899b49bc47b5e4ad443259d5bfe87/system_testing.py#L107

However, I think the current case is pretty confusing. See example above, where one has to know how the branch being used (`develop`) and the name of the Dockerfile (`-f Dockerfile.Ubuntu1604.home`) has to be translated to a tag (`-t $DOCKER_USERNAME/precice-ubuntu1604.home-develop`).

**My suggestion:** Don't use the command `docker build` for building the base images at all, but use something similar to [`system_testing.build`](https://github.com/precice/systemtests/blob/bf39313461b899b49bc47b5e4ad443259d5bfe87/system_testing.py#L19-L31) such that a python script can handle tagging and take care of cases. In the end this will allow us to use something like

```
python build_base.py -f Dockerfile.Ubuntu1604.home -b develop
```

instead of 

```
docker build -f Dockerfile.Ubuntu1604.home -t $DOCKER_USERNAME/precice-ubuntu1604.home-develop .
```

**Comment by BenjaminRodenberg** [comment]
I created a first draft and use it for all builds on [this branch](https://github.com/precice/systemtests/tree/draft_i77). I am still a bit unsure about the proper usage/purpose of the `$DOCKER_USERNAME` and the namespace `st_`.

**Comment by shkodm** [comment]
This is a nice idea, I like it. 
`$DOCKER_USERNAME` is basically just `precice`, but for some reason it was made Travis secret variable  although it is obvious, that it refers to `precice`, since we store all the images there. I never gotten around to remove it. Maybe it's time.. 
I have no idea about reasons behind `st_` namespace.

**Comment by BenjaminRodenberg** [comment]
The same problem shows up for `docker push`. Here, we should use something like `python3 push.py...`. To avoid mistakes like in de93de6daa664ba1d97400cf708f2b539363775a. In Travis you see what happened before this fix: https://travis-ci.org/precice/systemtests/jobs/555880409#L2669-L2670

**Comment by BenjaminRodenberg** [comment]
Is this issue still relevant? If yes, I can start working on it again. I just need somebody with a better overview to tell me whether this issue is already (partially) solved or not.

**Comment by BenjaminRodenberg** [comment]
We should additionally provide a script `push_base.py`.
