### ISSUE TITLE
Test PySolverInterface for python2 and python3

### ISSUE THREAD

**Issue by BenjaminRodenberg** [precice/systemtests#9]
* build PySolverInterface from https://github.com/precice/precice/tree/develop/src/precice/bindings/python to make sure that building works
* run dummy solver from https://github.com/precice/precice/tree/develop/tools/solverdummies/python to make sure that PySolverInterface can be used
* don't forget to do this for python2 and python3, since we want to support both

**Comment by floli** [comment]
This is partially already done in `Test_precice`

**Comment by BenjaminRodenberg** [comment]
I will try to take care of the rest. This is probably a good occasion to check out docker.

**Comment by floli** [comment]
Currently I get
```
Step 9/17 : RUN python setup.py build_ext --inplace
 ---> Running in 87094413dc98
Traceback (most recent call last):
  File "setup.py", line 7, in <module>
    from Cython.Distutils.build_ext import new_build_ext as build_ext
ImportError: cannot import name new_build_ext
The command '/bin/sh -c python setup.py build_ext --inplace' returned a non-zero code: 1
```

**Comment by BenjaminRodenberg** [comment]
When I pull the most recent version of the preCICE source, I get it working (see commit above). I do not know, if the way I extended the Dockerfile is ok or just a dirty hack.

**Comment by floli** [comment]
No, please don't change into precice root and explicitely pull. We should try to find out what you don't have the latest precice commit.

**Comment by BenjaminRodenberg** [comment]
I can now (8d7e18a017a34b141b4a8b6c9b59cc253db4eabb) run the solverdummies for python2/3 with the following commands:
```
docker build -t precice/precice:develop -f Dockerfile.precice .
cd Test_bindings
docker build -t precice_bindings -f Dockerfile .
```
Next step: put this into the existing python scripts for running the system tests.

**Comment by BenjaminRodenberg** [comment]
Commit 32f5a2d closes this issue.
