### ISSUE TITLE
Tolerance for numerical comparisons

### ISSUE THREAD

**Issue by MakisH** [precice/systemtests#90]
#89 added a very useful numerical comparison of the results against reference cases, a use case discussed in #19.

Now that we have this very good mechanism, we should discuss/communicate on the tolerance used for the comparisons. The default values are set in the file `compare_results.sh`:

https://github.com/precice/systemtests/blob/d36bb995194a3f0a3fb55ab93560cf230f23bc1c/compare_results.sh#L13-L14

and can be changed with input arguments in the same file. We currently use the default values (at least in `system_testing.py`).

We have to optimize this:
* having a too low tolerance would lead to tests failing without a good reason
* having a too high tolerance would lead to false successes, which could even accumulate

We currently have `max_diff_limit="0.01"`, but I would propose 1e-6 (without a very good reason). @shkodm @uekerman what do you think?

**Comment by shkodm** [comment]
As I mentioned in discussion for #87,  I only saw one test (Nutils-OpenFOAM) where this comparison was useful, so it is hard to judge what the tolerance should be. 

However the only way to find more tests where it matters and is to set tolerance to low. Then over time we can discover more failing tests and adjusts tolerance accordingly. If we set it to high, we might never discover failing tests.

So I am up for `1e-6` or similar value. I would just test if it works for Nutils-OpenFOAM test.

**Comment by shkodm** [comment]
Turned out, the only reasonable value to set was `1e-3`

**Comment by MakisH** [comment]
Did all the tests have a problem with lower tolerance or only Nutils? If this is the case, then can transform the tests so that we set a different tolerance for each test (or at least a default value, with an option to override it)?

**Comment by MakisH** [comment]
Did all the tests have a problem with lower tolerance or only Nutils? If this is the case, then can transform the tests so that we set a different tolerance for each test (or at least a default value, with an option to override it)?
